### ISSUE TITLE
Submit 2 photos

### ISSUE THREAD

**Issue by QD-lazy-tm** [MrWillCom/a-calendar#1]
Your photos: 

![IMG_8176](https://user-images.githubusercontent.com/65264970/128345183-b1b2c6d0-4811-461a-93bf-cfa6d85ecb9e.JPG)
![IMG_8177](https://user-images.githubusercontent.com/65264970/128345187-76cbf964-8c80-4831-974f-c07636cb561b.JPG)

License of your photo: CC BY-NC 4.0

Link to the license: https://creativecommons.org/licenses/by-nc/4.0/

Your name: Suzumiya Oriyuki

Your home page: https://github.com/QD-lazy-tm

Source URL of your photo (optional):

Description (optional):

**Comment by QD-lazy-tm** [comment]
Shot at Disney Resort, Shanghai

**Comment by MrWillCom** [comment]
Do you want to choose a date for each of your photos? It may appear on A Calendar tomorrow by default.

**Comment by QD-lazy-tm** [comment]
Any date is possible

**Comment by MrWillCom** [comment]
Congrats, your photos are added to A Calendar! 🎉 

At Commit 1fc013a

- [August 6 - A Calendar](https://a-calendar.vercel.app/20210806)
- [August 7 - A Calendar](https://a-calendar.vercel.app/20210807)
